# Importing required libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Loading training data from csv file and cleaning.

In [2]:
titanic_ds=pd.read_csv('titanic_x_y_train.csv').copy()
titanic_ds.head(15)


Pclass                                            Name     Sex   Age  \
0        2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1        3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2        2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3        3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4        3                          Sutehall, Mr. Henry Jr    male  25.0   
5        3                      Lemberopolous, Mr. Peter L    male  34.5   
6        1    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
7        3                              Jonkoff, Mr. Lalio    male  23.0   
8        2                    Williams, Mr. Charles Eugene    male   NaN   
9        3                        Rouse, Mr. Richard Henry    male  50.0   
10       3                 Stanley, Miss. Amy Zillah Elsie  female  23.0   
11       3                               Kassem, Mr. Fared    male   NaN   
12       2                         Fox, Mr. Stanley Hubert    male  36.0   
13       3                               Lennon, Mr. Denis    male   NaN   
14       3                      Healy, Miss. Hanora "Nora"  female   NaN   

    SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0       1      0           228414  26.0000   NaN        S         1  
1       0      0         A/5 2466   8.0500   NaN        S         0  
2       0      0           250655  26.0000   NaN        S         0  
3       0      4           349909  21.0750   NaN        S         0  
4       0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
5       0      0             2683   6.4375   NaN        C         0  
6       1      0           113803  53.1000  C123        S         1  
7       0      0           349204   7.8958   NaN        S         0  
8       0      0           244373  13.0000   NaN        S         1  
9       0      0         A/5 3594   8.0500   NaN        S         0  
10      0      0         CA. 2314   7.5500   NaN        S         1  
11      0      0             2700   7.2292   NaN        C         0  
12      0      0           229236  13.0000   NaN        S         0  
13      1      0           370371  15.5000   NaN        Q         0  
14      0      0           370375   7.7500   NaN        Q         1

In [3]:
titanic_ds.isnull().sum()

Pclass        0
Name          0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [4]:
Pnames=[]
for  i in titanic_ds.Name.values:
    if i.split(',')[1].split('.')[0].strip()=='Mrs':
        Pnames.append(3)
    elif i.split(',')[1].split('.')[0].strip()=='Mr':
        Pnames.append(2)
    elif i.split(',')[1].split('.')[0].strip()=='Miss':
        Pnames.append(1)
    elif i.split(',')[1].split('.')[0].strip()=='Master':
        Pnames.append(0)
    else:
        Pnames.append(4)
Pnames=np.array(Pnames,dtype=int)
Pnames

array([3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 2, 3, 1, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 0, 0, 2, 2, 2, 2, 3, 1,
       2, 2, 2, 2, 3, 2, 1, 0, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 2, 3, 1, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 1,
       3, 2, 3, 2, 1, 3, 3, 1, 2, 2, 2, 4, 2, 2, 2, 0, 2, 4, 3, 2, 4, 1,
       3, 2, 2, 2, 2, 1, 3, 2, 3, 0, 2, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 4, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 3, 2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 3, 1, 2, 2, 0, 2, 2, 2, 3, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 2, 2, 1, 3, 1, 0, 2, 2, 1, 2,

In [5]:
titanic_ds.describe(include='all')

Pclass                      Name   Sex         Age       SibSp  \
count   668.000000                       668   668  536.000000  668.000000   
unique         NaN                       668     2         NaN         NaN   
top            NaN  Thayer, Mr. John Borland  male         NaN         NaN   
freq           NaN                         1   427         NaN         NaN   
mean      2.296407                       NaN   NaN   29.700560    0.528443   
std       0.831638                       NaN   NaN   14.240257    1.080327   
min       1.000000                       NaN   NaN    0.670000    0.000000   
25%       2.000000                       NaN   NaN   21.000000    0.000000   
50%       3.000000                       NaN   NaN   29.000000    0.000000   
75%       3.000000                       NaN   NaN   38.250000    1.000000   
max       3.000000                       NaN   NaN   80.000000    8.000000   

             Parch Ticket        Fare Cabin Embarked    Survived  
count   668.000000    668  668.000000   154      667  668.000000  
unique         NaN    524         NaN   119        3         NaN  
top            NaN   1601         NaN    G6        S         NaN  
freq           NaN      6         NaN     4      484         NaN  
mean      0.407186    NaN   32.064552   NaN      NaN    0.402695  
std       0.854695    NaN   45.320835   NaN      NaN    0.490808  
min       0.000000    NaN    0.000000   NaN      NaN    0.000000  
25%       0.000000    NaN    7.925000   NaN      NaN    0.000000  
50%       0.000000    NaN   14.750000   NaN      NaN    0.000000  
75%       0.000000    NaN   31.275000   NaN      NaN    1.000000  
max       6.000000    NaN  512.329200   NaN      NaN    1.000000

In [6]:
titanic_ds.loc[titanic_ds['Sex']=='female','Sex']=0
titanic_ds.loc[titanic_ds['Sex']=='male','Sex']=1

In [7]:
titanic_ds.loc[titanic_ds['Embarked'].isnull(),'Embarked']='S'
titanic_ds.loc[titanic_ds['Embarked']=='S','Embarked']=1
titanic_ds.loc[titanic_ds['Embarked']=='C','Embarked']=2
titanic_ds.loc[titanic_ds['Embarked']=='Q','Embarked']=3
titanic_ds.loc[titanic_ds['Cabin'].isnull(),'Cabin']=0
titanic_ds.loc[titanic_ds['Cabin']!=0,'Cabin']=1



In [8]:
titanic_ds.loc[titanic_ds['Age'].isnull(),'Age']=titanic_ds['Age'].median(skipna=True)

In [9]:
titanic_ds.drop('Name',axis=1,inplace=True)
titanic_ds.drop('Ticket',axis=1,inplace=True)

In [10]:
titanic_ds.head(10)

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked  Survived
0       2    0  29.0      1      0  26.0000      0         1         1
1       3    1  29.0      0      0   8.0500      0         1         0
2       2    1  39.0      0      0  26.0000      0         1         0
3       3    0  29.0      0      4  21.0750      0         1         0
4       3    1  25.0      0      0   7.0500      0         1         0
5       3    1  34.5      0      0   6.4375      0         2         0
6       1    0  35.0      1      0  53.1000      1         1         1
7       3    1  23.0      0      0   7.8958      0         1         0
8       2    1  29.0      0      0  13.0000      0         1         1
9       3    1  50.0      0      0   8.0500      0         1         0

In [11]:
X_train=titanic_ds.values[:,:-1]
X_train=np.append(X_train,Pnames.reshape(-1,1),axis=1)
X_train.shape

(668, 9)

In [12]:
Y_train=titanic_ds.values[:,-1]
Y_train

array([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [13]:
print(X_train.shape,Y_train.shape)

(668, 9) (668,)


# Loading test data and cleaning it.

In [14]:
test_ds=pd.read_csv('titanic_x_test.csv').copy()
test_ds.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [15]:
Test_Pnmaes=[]
for i in test_ds.Name.values:
    if i.split(',')[1].split('.')[0].strip()=='Mrs':
        Test_Pnmaes.append(3)
    elif i.split(',')[1].split('.')[0].strip()=='Mr':
        Test_Pnmaes.append(2)
    elif i.split(',')[1].split('.')[0].strip()=='Miss':
        Test_Pnmaes.append(1)
    elif i.split(',')[1].split('.')[0].strip()=='Master':
        Test_Pnmaes.append(0)
    else:
        Test_Pnmaes.append(4)
Test_Pnmaes=np.array(Test_Pnmaes,dtype=int)
Test_Pnmaes
    

array([0, 4, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 1, 2, 4, 2,
       1, 0, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 2, 2, 2, 2, 4, 3, 1, 3, 2,
       2, 4, 1, 4, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 4, 4, 2, 2,
       2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 3, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1,
       3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 4,
       3, 2, 2])

In [16]:
test_ds.loc[test_ds['Sex']=='female','Sex']=0
test_ds.loc[test_ds['Sex']=='male','Sex']=1
test_ds.loc[test_ds['Embarked'].isnull(),'Embarked']='S'
test_ds.loc[test_ds['Embarked']=='S','Embarked']=1
test_ds.loc[test_ds['Embarked']=='C','Embarked']=2
test_ds.loc[test_ds['Embarked']=='Q','Embarked']=3
test_ds.loc[test_ds['Cabin'].isnull(),'Cabin']=0
test_ds.loc[test_ds['Cabin']!=0,'Cabin']=1

In [17]:
test_ds.loc[test_ds['Age'].isnull(),'Age']=test_ds['Age'].median(skipna=True)
test_ds.drop('Name',axis=1,inplace=True)
test_ds.drop('Ticket',axis=1,inplace=True)

In [18]:
X_test=test_ds.values
X_test=np.append(X_test,Test_Pnmaes.reshape(-1,1),axis=1)
X_test.shape

(223, 9)

In [19]:
X_test.shape

(223, 9)

# Logistic Regression

In [20]:
clf=LogisticRegression(solver='saga',max_iter=100000, tol=0.00001)
clf.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=1e-05, verbose=0,
                   warm_start=False)

In [21]:
clf.score(X_train,Y_train)

0.7934131736526946

In [22]:
predicted=clf.predict(X_test)

In [23]:
np.savetxt(X=predicted, delimiter=',', fname='titanic_ds predictions.csv', fmt='%.0f')